name: Build AutoTotem

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Create a GitHub release after building?"
        required: true
        default: "false"
        type: boolean

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.read_version.outputs.mod_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Read version from fabric.mod.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' src/main/resources/fabric.mod.json)
          echo "Version from fabric.mod.json: $VERSION"
          echo "mod_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build the mod
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoTotemMod
          path: build/libs/*.jar

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: AutoTotemMod
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: AutoTotem v${{ needs.build.outputs.version }}
          body: "Automatically built release"
          files: dist/*.jar
